networks:
  cncf-stack:

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - cncf-stack
      
  grafana:
    image: grafana/grafana
    user: "0"
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - cncf-stack
  
volumes:
  grafana: